version: '3.4'

services:

  postgresql_database:
    image: postgres:latest
    ports:
      - ${POSTGRES_OUT_PORT}:5432 # first is out, and 5432 is in
    env_file:
      - .env
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - ${PGADMIN_OUT_PORT}:80
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin

  api-server:
    depends_on:
      - "postgresql_database"
    build:
      context: .
      dockerfile: ./src/UniNote.Api/Dockerfile
    restart: always
    ports:
      - ${SERVER_OUT_PORT}:80
    env_file:
      - .env
    volumes:
      - api-server-static:/app/static

volumes:
  database-data:
  pgadmin:
  api-server-static:
